### ISSUE TITLE
使用9600语音的时候报一下错误

### ISSUE THREAD

**Issue by benben17** [nl8590687/ASRT_SpeechRecognition#100]
[*Info] Create Model Successful, Compiles Model Successful.
Traceback (most recent call last):
  File "test.py", line 39, in <module>
    r = ms.RecognizeSpeech_FromFile('D:\\ASRT_v0.5.0\\aaa.wav')
  File "D:\ASRT_v0.5.0\SpeechModel251.py", line 379, in RecognizeSpeech_FromFile
    r = self.RecognizeSpeech(wavsignal, fs)
  File "D:\ASRT_v0.5.0\SpeechModel251.py", line 348, in RecognizeSpeech
    data_input = GetFrequencyFeature3(wavsignal, fs)
  File "D:\ASRT_v0.5.0\general_function\file_wav.py", line 128, in GetFrequencyFeature3
    data_line = data_line * w # 加窗
ValueError: operands could not be broadcast together with shapes (320,) (400,)

**Comment by nl8590687** [comment]
请问9600语音是什么呢？

**Comment by phylony** [comment]
是采样率为9600么？

**Comment by benben17** [comment]
是的，还有在线文字转语音也是报这个错。
在线转语音是 音调5 音量5 语速5 ，转文字的时候也报上面这个错误

**Comment by nl8590687** [comment]
在线转语音？

**Comment by ForeverRoad** [comment]
operands could not be broadcast together with shapes (392,) (400,)我也报这个错误，是因为音频的问题吗？

**Comment by ForeverRoad** [comment]
是音频的采样率的问题，我的8000的不行，然后转换成22500的就好了
