### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: sequence_length(3) <= 200

### ISSUE THREAD

**Issue by xuchenxing** [nl8590687/ASRT_SpeechRecognition#113]
我按照AI柠檬的方法又给模型加上了aishell和primewords，但是在训练的时候，时不时的就会出现如下的错误，各位大神们能否帮看看是啥问题？ 

`Traceback (most recent call last):
  File "train_mspeech.py", line 51, in <module>
    ms.TrainModel(datapath, epoch = 50, batch_size = 64, save_step = 500)
  File "/home/yx/ASRT_SpeechRecognition/SpeechModel251.py", line 199, in TrainModel
    self._model.fit_generator(yielddatas, save_step)
  File "/home/yx/miniconda3/envs/tensorflow/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/yx/miniconda3/envs/tensorflow/lib/python3.5/site-packages/keras/engine/training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/yx/miniconda3/envs/tensorflow/lib/python3.5/site-packages/keras/engine/training_generator.py", line 213, in fit_generator
    class_weight=class_weight)
  File "/home/yx/miniconda3/envs/tensorflow/lib/python3.5/site-packages/keras/engine/training.py", line 1215, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/yx/miniconda3/envs/tensorflow/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2666, in __call__
    return self._call(inputs)
  File "/home/yx/miniconda3/envs/tensorflow/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2636, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/yx/miniconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1454, in __call__
    self._session._session, self._handle, args, status, None)
  File "/home/yx/miniconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: sequence_length(3) <= 200
	 [[Node: tower_1/model_2/ctc/CTCLoss = CTCLoss[_class=["loc:@training/Adam/gradients/tower_1/model_2/ctc/CTCLoss_grad/mul"], ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](tower_1/model_2/ctc/Log/_2285, tower_1/model_2/ctc/ToInt64/_2287, tower_1/model_2/ctc/ToInt32_2/_2289, tower_1/model_2/ctc/ToInt32_1/_2291)]]
	 [[Node: tower_2/model_2/ctc/boolean_mask_1/Squeeze/_1524 = _Send[T=DT_INT64, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:2", send_device_incarnation=1, tensor_name="edge_2972_tower_2/model_2/ctc/boolean_mask_1/Squeeze", _device="/job:localhost/replica:0/task:0/device:GPU:2"](tower_2/model_2/ctc/boolean_mask_1/Squeeze)]]
`

**Comment by xuchenxing** [comment]
基本上定位到是primewords的数据有问题， 因为不加载prime的数据就可以正常训练。 但是还是没查出来是哪里的问题， 其中是有一些音频过长的，我把音频长度截取了1600了。 看了代码里的200是定量，应该不会超啊， 不知道问题出在哪里。

**Comment by xuchenxing** [comment]
搞定了。 直接在代码里把音频长度截到1600没用， 后来直接把文件大小大于450k的全都去掉了， 就可以正常训练了， 但是还没理解原理是啥。。。可能CTC里的输入处理的问题。

**Comment by chenpe32cp** [comment]
我也遇到了同样的问题，感谢您的解决方法，请问用四个数据集后效果如何啊？

**Comment by HelloNel** [comment]
https://blog.csdn.net/chinatelecom08/article/details/82148647
我忘了不知道是不是batch_size太大的问题

**Comment by xuchenxing** [comment]
> 我也遇到了同样的问题，感谢您的解决方法，请问用四个数据集后效果如何啊？

加了数据效果有一点提升，不过导致收敛的速度非常慢，而且有点欠拟合了，正在考虑怎么加深一些模型深度
