### ISSUE TITLE
训练报错的问题

### ISSUE THREAD

**Issue by skeras** [nl8590687/ASRT_SpeechRecognition#12]
请教一下，我训练报如下错误是什么原因？谢谢~
python3 SpeechModel22.py 
[*提示] 创建模型成功，模型编译成功
Traceback (most recent call last):
  File "SpeechModel22.py", line 384, in <module>
    ms.LoadModel(modelpath + 'm22_2\\speech_model22_e_0_step_257000.model')
  File "SpeechModel22.py", line 178, in LoadModel
    self._model.load_weights(filename)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 2658, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'model_speech/m22_2\speech_model22_e_0_step_257000.model', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by nl8590687** [comment]
把SpeechModel22.py里面的第384行注释掉就行了，那个是用来加载已经训练的模型的，你还没训练，所以不需要执行那一行。
