### ISSUE TITLE
0.5.0 python test.py ValueError: Dimension 1 in both shapes must be equal, but are 1424 and 1422.

### ISSUE THREAD

**Issue by choupw** [nl8590687/ASRT_SpeechRecognition#129]
[*Info] Create Model Successful, Compiles Model Successful.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1864, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 1 in both shapes must be equal, but are 1424 and 1422. Shapes are [128,1424] and [128,1422]. for 'Assign_21' (op: 'Assign') with input shapes: [128,1424], [128,1422].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 32, in <module>
    ms.LoadModel(modelpath + 'm251/speech_model251_e_0_step_12000.model')
  File "/workspace/ASRT_SpeechRecognition-0.5.0/SpeechModel251.py", line 193, in LoadModel
    self._model.load_weights(filename)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 1058, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 2465, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py", line 1952, in assign
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/state_ops.py", line 227, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 66, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 2027, in __init__
    control_input_ops)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1867, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 1 in both shapes must be equal, but are 1424 and 1422. Shapes are [128,1424] and [128,1422]. for 'Assign_21' (op: 'Assign') with input shapes: [128,1424], [128,1422].

**Comment by nl8590687** [comment]
你是不是把下载的0.5版本和mater分支里面的文件混合起来用了？

**Comment by choupw** [comment]
> 你是不是把下载的0.5版本和mater分支里面的文件混合起来用了？

用0.5的模型，copy到0.5 sourcecode 下运行的

**Comment by nl8590687** [comment]
为什么要再放到source code下运行呢？原来的代码环境我是直接配置好的，直接运行就好了嘛，为什么要多此一举。
因为源码更新稍快一些，但是重新训练模型需要好长时间并需要花费很多的GPU计算成本，所以模型文件仍然沿用之前版本中的，所以不能把各种文件混合使用。
