### ISSUE TITLE
模型训练

### ISSUE THREAD

**Issue by huanzoey** [nl8590687/ASRT_SpeechRecognition#13]
您好，我用的speechmodel22 的模型，是不是我应该把385行的注释#去掉，先训练模型，再测试模型，
然后我在训练模型的时候，出现
496/500 [============================>.] - ETA: 24s - loss: 155.2476
497/500 [============================>.] - ETA: 18s - loss: 155.0813
498/500 [============================>.] - ETA: 12s - loss: 155.0358
499/500 [============================>.] - ETA: 6s - loss: 154.9670 
500/500 [==============================] - 3026s 6s/step - loss: 154.7819
*[测试结果] 语音识别 train 集语音单字错误率： 100.0 %
Traceback (most recent call last):
  File "D:/ASRT/ASRT_SpeechRecognition-master/SpeechModel22.py", line 385, in <module>
    ms.TrainModel(datapath, epoch = 50, batch_size =4, save_step = 500)
  File "D:/ASRT/ASRT_SpeechRecognition-master/SpeechModel22.py", line 172, in TrainModel
    self.TestModel(self.datapath, str_dataset='dev', data_count = 4)
  File "D:/ASRT/ASRT_SpeechRecognition-master/SpeechModel22.py", line 213, in TestModel
    data_input, data_labels = data.GetData((ran_num + i) % num_data)  # 从随机数开始连续向后取一定数量数据
  File "D:\ASRT\ASRT_SpeechRecognition-master\readdata22_2.py", line 141, in GetData
    wavsignal,fs=read_wav_data(self.datapath + filename)
  File "D:\ASRT\ASRT_SpeechRecognition-master\general_function\file_wav.py", line 21, in read_wav_data
    wav = wave.open(filename,"rb") # 打开一个wav格式的声音文件流
  File "D:\anaconda\anaconda3\lib\wave.py", line 499, in open
    return Wave_read(f)
  File "D:\anaconda\anaconda3\lib\wave.py", line 159, in __init__
    f = builtins.open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ASRT\\ASRT_SpeechRecognition-master\\dataset\\wav\\train\\A34\\A34_190.wav'

Process finished with exit code 1
可是数据集就是没有A34-190.WAV的。请问您有遇到过这个问题吗

**Comment by nl8590687** [comment]
这个我没有遇到过，因为我是一直用的之前旧版的THCHS30数据集的格式来做的。
但是，我刚才看了一下，在新版的THCHS30中，确实没有找到这个A34-190.WAV文件，因为这个文件被放到了dev目录下，只需要将其转移到train目录下即可，这应该是数据集的问题。同理，如果其他文件也有这样的问题，或者在测试模型的模式下遇到同样的问题，在其他目录下找到同名文件转移过去就好。

**Comment by huanzoey** [comment]
但是您给的train.wav.lst文件，train.syllablE文件也是没有这些音频的啊，那是不是这些文件也要把相应的列表添加上去呢

**Comment by QinCaofan** [comment]
Traceback (most recent call last):
  File "train_mspeech.py", line 47, in <module>
    ms.TrainModel(datapath, epoch = 50, batch_size = 4, save_step = 500)
  File "/home/qin/Downloads/ASRT_SpeechRecognition-master/SpeechModel22.py", line 203, in TrainModel
    self._model.fit_generator(yielddatas, save_step)
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.6-py3.5.egg/keras/legacy/interfaces.py", line 91, in wrapper
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.6-py3.5.egg/keras/engine/training.py", line 1421, in fit_generator
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.6-py3.5.egg/keras/engine/training_generator.py", line 155, in fit_generator
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.6-py3.5.egg/keras/utils/data_utils.py", line 793, in get
  File "/home/qin/.local/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.6-py3.5.egg/keras/utils/data_utils.py", line 658, in _data_generator_task
  File "/home/qin/Downloads/ASRT_SpeechRecognition-master/readdata22_2.py", line 199, in data_genetator
    data_input, data_labels = self.GetData((ran_num + i) % self.DataNum)  # 从随机数开始连续向后取一定数量数据
  File "/home/qin/Downloads/ASRT_SpeechRecognition-master/readdata22_2.py", line 141, in GetData
    wavsignal,fs=read_wav_data(self.datapath + filename)
  File "/home/qin/Downloads/ASRT_SpeechRecognition-master/general_function/file_wav.py", line 21, in read_wav_data
    wav = wave.open(filename,"rb") # 打开一个wav格式的声音文件流
  File "/usr/lib/python3.5/wave.py", line 499, in open
    return Wave_read(f)
  File "/usr/lib/python3.5/wave.py", line 159, in __init__
    f = builtins.open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/ST-CMDS-20170001_1-OS/20170001P00313A0022.wav'

**Comment by QinCaofan** [comment]
Traceback (most recent call last):
File "train_mspeech.py", line 47, in
ms.TrainModel(datapath, epoch = 50, batch_size = 4, save_step = 500)
File "/home/qin/Downloads/ASRT_SpeechRecognition-master/SpeechModel22.py", line 203, in TrainModel
self._model.fit_generator(yielddatas, save_step)
File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.6-py3.5.egg/keras/legacy/interfaces.py", line 91, in wrapper
File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.6-py3.5.egg/keras/engine/training.py", line 1421, in fit_generator
File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.6-py3.5.egg/keras/engine/training_generator.py", line 155, in fit_generator
File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.6-py3.5.egg/keras/utils/data_utils.py", line 793, in get
File "/home/qin/.local/lib/python3.5/site-packages/six.py", line 693, in reraise
raise value
File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.6-py3.5.egg/keras/utils/data_utils.py", line 658, in _data_generator_task
File "/home/qin/Downloads/ASRT_SpeechRecognition-master/readdata22_2.py", line 199, in data_genetator
data_input, data_labels = self.GetData((ran_num + i) % self.DataNum) # 从随机数开始连续向后取一定数量数据
File "/home/qin/Downloads/ASRT_SpeechRecognition-master/readdata22_2.py", line 141, in GetData
wavsignal,fs=read_wav_data(self.datapath + filename)
File "/home/qin/Downloads/ASRT_SpeechRecognition-master/general_function/file_wav.py", line 21, in read_wav_data
wav = wave.open(filename,"rb") # 打开一个wav格式的声音文件流
File "/usr/lib/python3.5/wave.py", line 499, in open
return Wave_read(f)
File "/usr/lib/python3.5/wave.py", line 159, in init
f = builtins.open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/ST-CMDS-20170001_1-OS/20170001P00313A0022.wav'
可是里面有啊

**Comment by nl8590687** [comment]
请cd到` ASRT_SpeechRecognition/ `目录下之后，再执行训练操作。

**Comment by memories666** [comment]
您好，我是一个刚接触语音识别的新手，在跑您代码时出现了下面这个问题，希望您有空的时候帮忙解答一下，谢谢。（dataset文件包括数据集和datalist目录下的文件）
[*提示] 创建模型成功，模型编译成功
  File "E:/ASRT_SpeechRecognition-master/SpeechModel24.py", line 400, in <module>
    ms.TrainModel(datapath, epoch = 50, batch_size = 16, save_step = 500)
  File "E:/ASRT_SpeechRecognition-master/SpeechModel24.py", line 145, in TrainModel
    data=DataSpeech(datapath, 'train') #数据使用训练集
  File "E:\ASRT_SpeechRecognition-master\readdata24.py", line 54, in __init__
    self.LoadDataList()
  File "E:\ASRT_SpeechRecognition-master\readdata24.py", line 90, in LoadDataList
    self.dic_wavlist_thchs30,self.list_wavnum_thchs30 = get_wav_list(self.datapath + filename_wavlist_thchs30)
  File "E:\ASRT_SpeechRecognition-master\general_function\file_wav.py", line 228, in get_wav_list
    txt_obj=open(filename,'r') # 打开文件并读入
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\ASRT_SpeechRecognition-master\\dataset.txt\\thchs30\\train.wav.lst'

Process finished with exit code 1

**Comment by huanzoey** [comment]
这是你的文件路径写错了，照着这个路径看有没有文件，或者文件名是不是写错了




---原始邮件---
发件人: "memories666"<notifications@github.com&gt;
发送时间: 2020年3月24日(周二) 晚上6:32
收件人: "nl8590687/ASRT_SpeechRecognition"<ASRT_SpeechRecognition@noreply.github.com&gt;;
抄送: "huanzoey"<2993766239@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [nl8590687/ASRT_SpeechRecognition] 模型训练 (#13)




 
您好，我是一个刚接触语音识别的新手，在跑您代码时出现了下面这个问题，希望您有空的时候帮忙解答一下，谢谢。（dataset文件包括数据集和datalist目录下的文件）
 [*提示] 创建模型成功，模型编译成功
 File "E:/ASRT_SpeechRecognition-master/SpeechModel24.py", line 400, in 
 ms.TrainModel(datapath, epoch = 50, batch_size = 16, save_step = 500)
 File "E:/ASRT_SpeechRecognition-master/SpeechModel24.py", line 145, in TrainModel
 data=DataSpeech(datapath, 'train') #数据使用训练集
 File "E:\ASRT_SpeechRecognition-master\readdata24.py", line 54, in init
 self.LoadDataList()
 File "E:\ASRT_SpeechRecognition-master\readdata24.py", line 90, in LoadDataList
 self.dic_wavlist_thchs30,self.list_wavnum_thchs30 = get_wav_list(self.datapath + filename_wavlist_thchs30)
 File "E:\ASRT_SpeechRecognition-master\general_function\file_wav.py", line 228, in get_wav_list
 txt_obj=open(filename,'r') # 打开文件并读入
 FileNotFoundError: [Errno 2] No such file or directory: 'E:\ASRT_SpeechRecognition-master\dataset.txt\thchs30\train.wav.lst'
 
Process finished with exit code 1

**Comment by memories666** [comment]
谢谢您，问题已经解决。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"huanzoey"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月24日(星期二) 晚上6:40
收件人:&nbsp;"nl8590687/ASRT_SpeechRecognition"<ASRT_SpeechRecognition@noreply.github.com&gt;;
抄送:&nbsp;"kd"<260174826@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [nl8590687/ASRT_SpeechRecognition] 模型训练 (#13)





 这是你的文件路径写错了，照着这个路径看有没有文件，或者文件名是不是写错了 
 
 
 
 
 ---原始邮件--- 
 发件人: "memories666"<notifications@github.com&amp;gt; 
 发送时间: 2020年3月24日(周二) 晚上6:32 
 收件人: "nl8590687/ASRT_SpeechRecognition"<ASRT_SpeechRecognition@noreply.github.com&amp;gt;; 
 抄送: "huanzoey"<2993766239@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题: Re: [nl8590687/ASRT_SpeechRecognition] 模型训练 (#13) 
 
 
 
 
   
 您好，我是一个刚接触语音识别的新手，在跑您代码时出现了下面这个问题，希望您有空的时候帮忙解答一下，谢谢。（dataset文件包括数据集和datalist目录下的文件） 
  [*提示] 创建模型成功，模型编译成功 
  File "E:/ASRT_SpeechRecognition-master/SpeechModel24.py", line 400, in  
  ms.TrainModel(datapath, epoch = 50, batch_size = 16, save_step = 500) 
  File "E:/ASRT_SpeechRecognition-master/SpeechModel24.py", line 145, in TrainModel 
  data=DataSpeech(datapath, 'train') #数据使用训练集 
  File "E:\ASRT_SpeechRecognition-master\readdata24.py", line 54, in init 
  self.LoadDataList() 
  File "E:\ASRT_SpeechRecognition-master\readdata24.py", line 90, in LoadDataList 
  self.dic_wavlist_thchs30,self.list_wavnum_thchs30 = get_wav_list(self.datapath + filename_wavlist_thchs30) 
  File "E:\ASRT_SpeechRecognition-master\general_function\file_wav.py", line 228, in get_wav_list 
  txt_obj=open(filename,'r') # 打开文件并读入 
  FileNotFoundError: [Errno 2] No such file or directory: 'E:\ASRT_SpeechRecognition-master\dataset.txt\thchs30\train.wav.lst' 
   
 Process finished with exit code 1

**Comment by Yjundayi** [comment]
我的环境是windows，将config把没有的数据集配置删除，然后注意“data_path”这里的斜线

{
    "dict_filename": "dict.txt",

    "dataset":{
        "train":[
            {
                "name": "thchs30_train",
                "data_list": "datalist/thchs30/train.wav.lst",
                "data_path": "data/speech_data/",
                "label_list": "datalist/thchs30/train.syllable.txt"
            }
        ],

        "dev":[
            {
                "name": "thchs30_dev",
                "data_list": "datalist/thchs30/cv.wav.lst",
                "data_path": "data/speech_data/",
                "label_list": "datalist/thchs30/cv.syllable.txt"
            }
        ],

        "test":[
            {
                "name": "thchs30_test",
                "data_list": "datalist/thchs30/test.wav.lst",
                "data_path": "data/speech_data/",
                "label_list": "datalist/thchs30/test.syllable.txt"
            }
        ]
    }
}
