### ISSUE TITLE
训练样本长度的问题

### ISSUE THREAD

**Issue by genghuan2005** [nl8590687/ASRT_SpeechRecognition#134]
我自己添加了两个公开数据集，训练的时候报错：
Traceback (most recent call last):
  File "/home/import/anaconda3/envs/pyAsrt/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/import/anaconda3/envs/pyAsrt/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/import/anaconda3/envs/pyAsrt/lib/python3.6/site-packages/keras/engine/training.py", line 612, in data_generator_task
    generator_output = next(self._generator)
  File "/home/import/gh/ASRT/ASRT_SpeechRecognition/readdata24.py", line 366, in data_genetator
    X[i,0:len(data_input)] = data_input
ValueError: could not broadcast input array from shape (1677,200,1) into shape (1600,200,1)
样本长度设置为1600是什么原因 如果遇到大于1600的样本该如何处理呢

**Comment by nl8590687** [comment]
从报错信息上看，那条训练数据的时间长度大于16秒，由于时间长度超过的数据量一般较少，可以通过从文件目录和数据列表文件以及对应的标签文件中删除这一条数据来解决。如果数据集中大量存在超过16秒的数据，最佳的方法是切分成若干短于16秒的音频后再使用。
