### ISSUE TITLE
Bug，请问楼主，报错这个吗TypeError: __init__() missing 1 required positional argument: 'nb_col'

### ISSUE THREAD

**Issue by ttanzhiqiang** [nl8590687/ASRT_SpeechRecognition#16]
C:\Users\Administrator\Desktop\ASRT_v0.1>python3 test_mspeech.py
Using TensorFlow backend.
2018-06-03 20:38:53.581395: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-06-03 20:38:53.617397: E T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_UNKNOWN
2018-06-03 20:38:53.637398: I T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: USER-20171121WK
2018-06-03 20:38:53.638398: I T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_diagnostics.cc:165] hostname: USER-20171121WK
Traceback (most recent call last):
  File "test_mspeech.py", line 45, in <module>
    ms = ModelSpeech(datapath)
  File "C:\Users\Administrator\Desktop\ASRT_v0.1\SpeechModel22.py", line 48, in __init__
    self._model, self.base_model = self.CreateModel()
  File "C:\Users\Administrator\Desktop\ASRT_v0.1\SpeechModel22.py", line 84, in CreateModel
    layer_h1 = Conv2D(32, (3,3), use_bias=True, activation='relu', padding='same', kernel_initializer='he_normal')(input_data) # 卷积层
TypeError: __init__() missing 1 required positional argument: 'nb_col'

**Comment by nl8590687** [comment]
根据这个报错，请检查CUDA环境是否正确安装
以及Keras和Tensorflow的版本是否对应，建议直接安装Tensorflow和Keras的最新版本，如果GPU只能支持CUDA8.9，那么Tensorflow请安装1.4及以上的版本，Keras安装最新版。

**Comment by ttanzhiqiang** [comment]
谢谢
