### ISSUE TITLE
運行的過程中出現這個問題

### ISSUE THREAD

**Issue by Sean861026** [nl8590687/ASRT_SpeechRecognition#17]
Traceback (most recent call last):
  File "asrserver.py", line 16, in <module>
    ms = ModelSpeech(datapath)
  File "C:\ASRT_SpeechRecognition-master\SpeechModel24.py", line 39, in __init__
    self._model, self.base_model = self.CreateModel()
  File "C:\ASRT_SpeechRecognition-master\SpeechModel24.py", line 126, in CreateModel
    test_func = K.function([input_data], [y_pred])
  File "C:\Users\bub20\AppData\Local\Programs\Python\Python36\lib\site-packages\keras-2.1.6-py3.6.egg\keras\backend\theano_backend.py", line 1248, in function
  File "C:\Users\bub20\AppData\Local\Programs\Python\Python36\lib\site-packages\keras-2.1.6-py3.6.egg\keras\backend\theano_backend.py", line 1234, in __init__
  File "C:\Users\bub20\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\Users\bub20\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\Users\bub20\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\compile\function_module.py", line 1839, in orig_function
    name=name)
  File "C:\Users\bub20\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\compile\function_module.py", line 1487, in __init__
    accept_inplace)
  File "C:\Users\bub20\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\compile\function_module.py", line 181, in std_fgraph
    update_mapping=update_mapping)
  File "C:\Users\bub20\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\gof\fg.py", line 175, in __init__
    self.__import_r__(output, reason="init")
  File "C:\Users\bub20\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\gof\fg.py", line 346, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "C:\Users\bub20\AppData\Local\Programs\Python\Python36\lib\site-packages\theano\gof\fg.py", line 391, in __import__
    raise MissingInputError(error_msg, variable=r)
theano.gof.fg.MissingInputError: Input 0 of the graph (indices start from 0), used to compute if{}(keras_learning_phase, Elemwise{true_div,no_inplace}.0, Elemwise{mul,no_inplace}.0), was not provided and not given a value. Use the Theano flag exception_verbosity='high', for more information on this error.

Backtrace when that variable is created:

  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\Users\bub20\AppData\Local\Programs\Python\Python36\lib\site-packages\keras-2.1.6-py3.6.egg\keras\backend\__init__.py", line 81, in <module>
    from .theano_backend import *
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\Users\bub20\AppData\Local\Programs\Python\Python36\lib\site-packages\keras-2.1.6-py3.6.egg\keras\backend\theano_backend.py", line 34, in <module>
    _LEARNING_PHASE = T.scalar(dtype='uint8', name='keras_learning_phase')  # 0 = test, 1 = train

**Comment by nl8590687** [comment]
您好，從這個報錯問題的輸出內容來看，應該是您使用的Keras的後端的問題，本項目需要使用TensorFlow作為Keras的後端backend，而不是Theano，請安裝TensorFlow并將Keras切換到TF後端程式即可正常運行。

**Comment by Sean861026** [comment]
我有安裝TENSORFLOW
![image](https://user-images.githubusercontent.com/38836267/40955464-d419789e-68bc-11e8-9ad8-9ba349472096.png)

**Comment by Sean861026** [comment]
謝謝 已解決
