### ISSUE TITLE
wave.Error: file does not start with RIFF id

### ISSUE THREAD

**Issue by TLHorse** [nl8590687/ASRT_SpeechRecognition#183]
我下载的是您的模型训练好的版本，然后我运行了`test.py`。由于系统路径兼容的问题，我对`test.py`稍作更改如下：
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
@author: nl8590687
用于测试整个一套语音识别系统的程序
语音模型 + 语言模型
"""
import platform as plat
from os import getcwd

from SpeechModel251 import ModelSpeech
from LanguageModel2 import ModelLanguage
from keras import backend as K

datapath = getcwd()
# modelpath = 'model_speech'

# system_type = plat.system() # 由于不同的系统的文件路径表示不一样，需要进行判断
# if system_type == 'Windows':
# 	datapath = '.'
# 	modelpath = modelpath + '\\'
# elif system_type == 'Linux':
# 	datapath = '.'
# 	modelpath = modelpath + '/'
# else:
# 	print('*[Message] Unknown System\n')
# 	datapath = 'dataset'
# 	modelpath = modelpath + '/'

ms = ModelSpeech(datapath)

ms.LoadModel("/Users/MaTianlai/Downloads/ASRT_v0.6.1/model_speech/speech_model251_e_0_step_625000.model")

#ms.TestModel(datapath, str_dataset='test', data_count = 64, out_report = True)
r = ms.RecognizeSpeech_FromFile('/Users/MaTianlai/Downloads/ASRT_v0.6.1/resources/test.mp3')

K.clear_session()

print('*[提示] 语音识别结果：\n',r)

ml = ModelLanguage('model_language')
ml.LoadModel()
str_pinyin = r
r = ml.SpeechToText(str_pinyin)
print('语音转文字结果：\n',r)
```
运行了一下，结果提示`wav`错误：
```bash
Traceback (most recent call last):
  File "/Users/MaTianlai/Downloads/ASRT_v0.6.1/test.py", line 35, in <module>
    r = ms.RecognizeSpeech_FromFile('/Users/MaTianlai/Downloads/ASRT_v0.6.1/resources/test.mp3')
  File "/Users/MaTianlai/Downloads/ASRT_v0.6.1/SpeechModel251.py", line 380, in RecognizeSpeech_FromFile
    wavsignal,fs = read_wav_data(filename)
  File "/Users/MaTianlai/Downloads/ASRT_v0.6.1/general_function/file_wav.py", line 21, in read_wav_data
    wav = wave.open(filename,"rb") # 打开一个wav格式的声音文件流
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/wave.py", line 510, in open
    return Wave_read(f)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/wave.py", line 164, in __init__
    self.initfp(f)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/wave.py", line 131, in initfp
    raise Error('file does not start with RIFF id')
wave.Error: file does not start with RIFF id
```
请问该怎么解决？

**Comment by TLHorse** [comment]
后续跟进：
我又试着在CSDN找了[解决方案](https://blog.csdn.net/appleyuchi/article/details/78486179)，使用
```bash
ffmpeg -i out_test7.mp3 out_test7.wav
```
命令从`.mp3`转换到`.wav`。可是这次运行却报了如下错误：
```bash
Traceback (most recent call last):
  File "/Users/MaTianlai/Downloads/ASRT_v0.6.1/test.py", line 35, in <module>
    r = ms.RecognizeSpeech_FromFile('/Users/MaTianlai/Downloads/ASRT_v0.6.1/resources/test.wav')
  File "/Users/MaTianlai/Downloads/ASRT_v0.6.1/SpeechModel251.py", line 382, in RecognizeSpeech_FromFile
    r = self.RecognizeSpeech(wavsignal, fs)
  File "/Users/MaTianlai/Downloads/ASRT_v0.6.1/SpeechModel251.py", line 351, in RecognizeSpeech
    data_input = GetFrequencyFeature3(wavsignal, fs)
  File "/Users/MaTianlai/Downloads/ASRT_v0.6.1/general_function/file_wav.py", line 117, in GetFrequencyFeature3
    raise ValueError('[Error] ASRT currently only supports wav audio files with a sampling rate of 16000 Hz, but this audio is ' + str(fs) + ' Hz. ')
ValueError: [Error] ASRT currently only supports wav audio files with a sampling rate of 16000 Hz, but this audio is 48000 Hz.
```
看来像是我的`.wav`文件不是16000赫兹，所以不能识别。那么我怎样能更改赫兹频率呢？

**Comment by TLHorse** [comment]
我解决了！解决方法（运行如下命令）：
```bash
$ ffmpeg -i test.mp3 out_test.wav
$ ffmpeg -i out_test.wav -ar 16000 out_test-16k.wav
```
