### ISSUE TITLE
训练报错，specified in either feed_devices or fetch_devices was not found in the Graph

### ISSUE THREAD

**Issue by JIANG3330** [nl8590687/ASRT_SpeechRecognition#191]
![image](https://user-images.githubusercontent.com/42256557/82965352-757d2e80-9ffa-11ea-8dc1-abe3158d17a2.png)

2020-05-27 01:02:04.419862: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10869 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0001:00:00.0, compute capability: 3.7)
Traceback (most recent call last):
  File "train_mspeech.py", line 48, in <module>
    ms.TrainModel(datapath, epoch = 50, batch_size = 16, save_step = 500)
  File "/root/ASRT_SpeechRecognition/SpeechModel251.py", line 187, in TrainModel
    self.TestModel(self.datapath, str_dataset='train', data_count = 4)
  File "/root/ASRT_SpeechRecognition/SpeechModel251.py", line 250, in TestModel
    pre = self.Predict(data_input, data_input.shape[0] // 8)
  File "/root/ASRT_SpeechRecognition/SpeechModel251.py", line 305, in Predict
    base_pred = self.base_model.predict(x = x_in)
  File "/anaconda/envs/python36/lib/python3.6/site-packages/keras/engine/training.py", line 1462, in predict
    callbacks=callbacks)
  File "/anaconda/envs/python36/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 324, in predict_loop
    batch_outs = f(ins_batch)
  File "/anaconda/envs/python36/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3473, in __call__
    self._make_callable(feed_arrays, feed_symbols, symbol_vals, session)
  File "/anaconda/envs/python36/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3410, in _make_callable
    callable_fn = session._make_callable_from_options(callable_opts)
  File "/anaconda/envs/python36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1505, in _make_callable_from_options
    return BaseSession._Callable(self, callable_options)
  File "/anaconda/envs/python36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1460, in __init__
    session._session, options_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Tensor the_input:0, specified in either feed_devices or fetch_devices was not found in the Graph

**Comment by JIANG3330** [comment]
已解决，tensorflow版本降到1.13.1后能运行
