### ISSUE TITLE
测试报错

### ISSUE THREAD

**Issue by hanhongshen** [nl8590687/ASRT_SpeechRecognition#20]
Using TensorFlow backend.
[*提示] 创建模型成功，模型编译成功
测试进度： 0 / 128
测试进度： 10 / 128
测试进度： 20 / 128
测试进度： 30 / 128
测试进度： 40 / 128
测试进度： 50 / 128
测试进度： 60 / 128
测试进度： 70 / 128
测试进度： 80 / 128
测试进度： 90 / 128
测试进度： 100 / 128
测试进度： 110 / 128
测试进度： 120 / 128
*[测试结果] 语音识别 test 集语音单字错误率： 30.01432664756447 %
Traceback (most recent call last):
  File "test_mspeech.py", line 55, in <module>
    r = ms.RecognizeSpeech_FromFile('/root/ffdwd1.wav')
  File "/data/ASRT_SpeechRecognition-0.3/SpeechModel25.py", line 357, in RecognizeSpeech_FromFile
    r = self.RecognizeSpeech(wavsignal, fs)
  File "/data/ASRT_SpeechRecognition-0.3/SpeechModel25.py", line 337, in RecognizeSpeech
    r1 = self.Predict(data_input, input_length)
  File "/data/ASRT_SpeechRecognition-0.3/SpeechModel25.py", line 276, in Predict
    x_in[i,0:len(data_input)] = data_input
ValueError: could not broadcast input array from shape (43059,200,1) into shape (1600,200,1)

**Comment by nl8590687** [comment]
应该是你的wav文件的录音时间长度太长了，请确保wav文件录音时间长度小于16秒。如果时间超出，请分割成两个文件来识别。
