### ISSUE TITLE
模型训练报错

### ISSUE THREAD

**Issue by Bonifacez** [nl8590687/ASRT_SpeechRecognition#201]
Traceback (most recent call last):
  File "D:/Files/zbj/语音识别/ASRT/SpeechModel251.py", line 434, in <module>
    ms.TestModel()
  File "D:/Files/zbj/语音识别/ASRT/SpeechModel251.py", line 259, in TestModel
    pre = self.Predict(data_input, data_input.shape[0] // 8)
  File "D:/Files/zbj/语音识别/ASRT/SpeechModel251.py", line 338, in Predict
    r1 = r[0][0].eval(toNumpySess)#session=tf.compat.v1.Session()
  File "D:\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1129, in eval
    "eval is not supported when eager execution is enabled, "
NotImplementedError: eval is not supported when eager execution is enabled, is .numpy() what you're looking for?

一时不知道怎么办，求助，百度谷歌都没找到合适的解决办法。

**Comment by nl8590687** [comment]
你的软件包环境是什么样的

**Comment by Bonifacez** [comment]
tf 2.1.0
Keras 2.3.1
您回复也太快了

**Comment by Bonifacez** [comment]
呃，问题解决了，不使用r[0][0].eval()，而使用r[0][0].numpy()就行了，虽然很头疼，不过，感谢。

**Comment by cheukfaii** [comment]
> 呃，问题解决了，不使用r[0][0].eval()，而使用r[0][0].numpy()就行了，虽然很头疼，不过，感谢。

请问一下为什么我改了这还是报错了
