### ISSUE TITLE
运行test_mspeech.py报错

### ISSUE THREAD

**Issue by zcy618** [nl8590687/ASRT_SpeechRecognition#202]
我下载了最新的master代码，解压了数据，然后训练也可以跑起来：
[*Info] Create Model Successful, Compiles Model Successful. 
[running] train epoch 0 .
[message] epoch 0 . Have train datas 0+
Epoch 1/1
500/500 [==============================] - 7968s 16s/step - loss: 87.1636

但是一个运行测试python3 test_mspeech.py就报错如下：
[*Info] Create Model Successful, Compiles Model Successful. 
Test Count:  0 / 128
Traceback (most recent call last):
  File "test_mspeech.py", line 51, in <module>
    ms.TestModel(datapath, str_dataset='test', data_count = 128, out_report = True)
  File "/home/parallels/Desktop/asr/ASRT_SpeechRecognition/SpeechModel251.py", line 250, in TestModel
    pre = self.Predict(data_input, data_input.shape[0] // 8)
  File "/home/parallels/Desktop/asr/ASRT_SpeechRecognition/SpeechModel251.py", line 305, in Predict
    base_pred = self.base_model.predict(x = x_in)
  File "/home/parallels/Desktop/asr/asrt-train-env/lib/python3.6/site-packages/keras/engine/training.py", line 1462, in predict
    callbacks=callbacks)
  File "/home/parallels/Desktop/asr/asrt-train-env/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 324, in predict_loop
    batch_outs = f(ins_batch)
  File "/home/parallels/Desktop/asr/asrt-train-env/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3473, in __call__
    self._make_callable(feed_arrays, feed_symbols, symbol_vals, session)
  File "/home/parallels/Desktop/asr/asrt-train-env/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3410, in _make_callable
    callable_fn = session._make_callable_from_options(callable_opts)
  File "/home/parallels/Desktop/asr/asrt-train-env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1505, in _make_callable_from_options
    return BaseSession._Callable(self, callable_options)
  File "/home/parallels/Desktop/asr/asrt-train-env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1460, in __init__
    session._session, options_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Tensor the_input:0, specified in either feed_devices or fetch_devices was not found in the Graph

这是什么原因？我代码也没有改过，看不懂要哪里再配置一下吗？
Thanks.

**Comment by nl8590687** [comment]
已经解决了，请重新克隆最新的master代码试试
