### ISSUE TITLE
语音片段长度

### ISSUE THREAD

**Issue by XinzheTing** [nl8590687/ASRT_SpeechRecognition#222]
测试的时候输入的语音片段长度时固定的吗？我使用test.py测试一个十几分钟的语音文件显示格式大小不匹配。
`Traceback (most recent call last):
  File "test.py", line 34, in <module>
    r = ms.RecognizeSpeech_FromFile('/home/user/XiJing/XiJing (1)/音频1.wav')
  File "/home/user/ASRT_v0.6.1/SpeechModel251.py", line 382, in RecognizeSpeech_FromFile
    r = self.RecognizeSpeech(wavsignal, fs)
  File "/home/user/ASRT_v0.6.1/SpeechModel251.py", line 362, in RecognizeSpeech
    r1 = self.Predict(data_input, input_length)
  File "/home/user/ASRT_v0.6.1/SpeechModel251.py", line 304, in Predict
    base_pred = self.base_model.predict(x = x_in)
  File "/home/user/anaconda3/envs/ml/lib/python3.6/site-packages/keras/engine/training.py", line 1441, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/home/user/anaconda3/envs/ml/lib/python3.6/site-packages/keras/engine/training.py", line 579, in _standardize_user_data
    exception_prefix='input')
  File "/home/user/anaconda3/envs/ml/lib/python3.6/site-packages/keras/engine/training_utils.py", line 145, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected the_input to have shape (1600, 200, 1) but got array with shape (164184, 200, 1)`

**Comment by nl8590687** [comment]
一次预测音频长度不能超过16秒，如果超过的请先做切分

**Comment by Jefferyoung96** [comment]
是这个样子，我想用自己的数据训练模型，修改了代码，这个对音频的长度还是有不超过16s的要求吗？如果修改作者您对于16s的设置是不是有可能？

**Comment by Jefferyoung96** [comment]
> 一次预测音频长度不能超过16秒，如果超过的请先做切分

是这个样子，我想用自己的数据训练模型，修改了代码，这个对音频的长度还是有不超过16s的要求吗？如果修改作者您对于16s的设置是不是有可能？

**Comment by nl8590687** [comment]
> 是这个样子，我想用自己的数据训练模型，修改了代码，这个对音频的长度还是有不超过16s的要求吗？如果修改作者您对于16s的设置是不是有可能？
你自己的数据的话，可以考虑将时长调大，但是如果调大太多，你的CPU和GPU的Memory大概率是不够用的，除了现有的数据集都是16秒以内的缘故外，不是我不想调大，是Memory不够用，数据流尺寸已经比计算机视觉的图片数据大太多了，再调大尺寸，现有的绝大部分GPU就都不够用了。
@Jefferyoung96
