### ISSUE TITLE
安装好了没法用

### ISSUE THREAD

**Issue by ytian** [nl8590687/ASRT_SpeechRecognition#226]
将test.py里面修改我自己的音频文件测试，然后执行python test.py，直接报错：
2020-12-24 13:49:05.617488: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
WARNING:tensorflow:From /Users/sun/anaconda3/envs/asrt/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

[*Info] Create Model Successful, Compiles Model Successful.
*[Message] Unknown System

Traceback (most recent call last):
  File "test.py", line 35, in <module>
    r = ms.RecognizeSpeech_FromFile('/Users/sun/AI/data/deepspeech/testvideo/xinwen-16000-1.wav')
  File "/Users/sun/AI/models/asrt/ASRT_v0.6.1/SpeechModel251.py", line 382, in RecognizeSpeech_FromFile
    r = self.RecognizeSpeech(wavsignal, fs)
  File "/Users/sun/AI/models/asrt/ASRT_v0.6.1/SpeechModel251.py", line 362, in RecognizeSpeech
    r1 = self.Predict(data_input, input_length)
  File "/Users/sun/AI/models/asrt/ASRT_v0.6.1/SpeechModel251.py", line 301, in Predict
    x_in[i,0:len(data_input)] = data_input
ValueError: could not broadcast input array from shape (18482,200,1) into shape (1600,200,1)

**Comment by ytian** [comment]
查了下，是时间问题，只能最少16秒，问题关闭。
