### ISSUE TITLE
dict.txt是哪个文件

### ISSUE THREAD

**Issue by 1973719588** [nl8590687/ASRT_SpeechRecognition#238]
模型训练好了，也能够测试，在自己test自己录的语音的时候，显示dataset无dict.txt文件

请问这个文件是什么？在哪儿下载？

[*Info] Create Model Successful, Compiles Model Successful. 
Traceback (most recent call last):
  File "/home/gong/zyb1/ASRT/ASRT_SpeechRecognition/test.py", line 35, in <module>
    r = ms.RecognizeSpeech_FromFile('dataset_test/20170001P00023A0007.wav')
  File "/home/gong/zyb1/ASRT/ASRT_SpeechRecognition/SpeechModel251.py", line 372, in RecognizeSpeech_FromFile
    r = self.RecognizeSpeech(wavsignal, fs)
  File "/home/gong/zyb1/ASRT/ASRT_SpeechRecognition/SpeechModel251.py", line 355, in RecognizeSpeech
    list_symbol_dic = GetSymbolList(self.datapath) # 获取拼音列表
  File "/home/gong/zyb1/ASRT/ASRT_SpeechRecognition/general_function/file_dict.py", line 17, in GetSymbolList
    txt_obj=open(datapath + 'dict.txt','r',encoding='UTF-8') # 打开文件并读入
FileNotFoundError: [Errno 2] No such file or directory: 'dataset//dict.txt'

Process finished with exit code 1

**Comment by nl8590687** [comment]
请跟着文档中的教程步骤来做，教程资源在Readme文档和ASRT项目文档上都有

**Comment by 1973719588** [comment]
您好，我就是按照文档的教程来操作了，然后dataset里的文件有datalist的两个文件和两个数据集，没有dict.txt这个文件，打扰您了哈~

**Comment by 1973719588** [comment]
不好意思，我仔细阅读了一遍，明白了~谢谢
打扰了哈~
