### ISSUE TITLE
测试时候报错： ValueError: operands could not be broadcast together with shapes (320,) (400,) ，什么原因？请问怎么解决？谢谢

### ISSUE THREAD

**Issue by shikongy** [nl8590687/ASRT_SpeechRecognition#27]
Traceback (most recent call last):
  File "E:\百度云同步盘\pythonProjects\ASRT_v0.3\test.py", line 40, in <module>
    r = ms.RecognizeSpeech_FromFile('E:\\10086.wav')
  File "E:\百度云同步盘\pythonProjects\ASRT_v0.3\SpeechModel25.py", line 357, in RecognizeSpeech_FromFile
    r = self.RecognizeSpeech(wavsignal, fs)
  File "E:\百度云同步盘\pythonProjects\ASRT_v0.3\SpeechModel25.py", line 326, in RecognizeSpeech
    data_input = GetFrequencyFeature3(wavsignal, fs)
  File "E:\百度云同步盘\pythonProjects\ASRT_v0.3\general_function\file_wav.py", line 128, in GetFrequencyFeature3
    data_line = data_line * w # 加窗
ValueError: operands could not be broadcast together with shapes (320,) (400,)

**Comment by nl8590687** [comment]
请首先检查一下音频文件格式，是否为16kHz，单声道，16bit
其次，请检查一下代码在下载后是否被更改
如果一切均正常，理论上是不会有这样的问题的

**Comment by shikongy** [comment]
请问你们都用什么软件录制 16kHz，单声道，16bit 这样的文件？谢谢

**Comment by shikongy** [comment]
@nl8590687 非常感谢

**Comment by shikongy** [comment]
@nl8590687 方便您可以给我留个qq或者微信吗？谢谢

**Comment by shikongy** [comment]
我用recforge软件录制，解决此问题

**Comment by nl8590687** [comment]
qq的话，请直接进群吧 详见那个issue
