### ISSUE TITLE
No such file or directory（训练每次出现的缺失wav文件还不一样）

### ISSUE THREAD

**Issue by xuanxuanzl** [nl8590687/ASRT_SpeechRecognition#317]
环境：
WIN11
nivadaRTX4090*1
PYTHON3.9。16
tensortflow-gpu:2.8.0
cuda:11.2(装有多个版本，还有11.8，系统变量配置为了11.2)

**第一次运行：**

C:\Users\Admin\.conda\envs\ASRT_Speech\python.exe C:/PROJECT-AV-ASR/ASRT_SpeechRecognition-master/train_speech_model.py
2023-05-01 13:43:48.403865: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-01 13:43:48.687455: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21350 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4090, pci bus id: 0000:01:00.0, compute capability: 8.9
[ASRT] Compiles Model Successfully.
[ASRT Training] train epoch 1/50 .
C:\PROJECT-AV-ASR\ASRT_SpeechRecognition-master\speech_model.py:120: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  self.trained_model.fit_generator(yielddatas, num_iterate, callbacks=call_back)
Traceback (most recent call last):
  File "C:\PROJECT-AV-ASR\ASRT_SpeechRecognition-master\train_speech_model.py", line 50, in <module>
    ms.train_model(optimizer=opt, data_loader=train_data,
  File "C:\PROJECT-AV-ASR\ASRT_SpeechRecognition-master\speech_model.py", line 120, in train_model
    self.trained_model.fit_generator(yielddatas, num_iterate, callbacks=call_back)
  File "C:\Users\Admin\.conda\envs\ASRT_Speech\lib\site-packages\keras\engine\training.py", line 2209, in fit_generator
    return self.fit(
  File "C:\Users\Admin\.conda\envs\ASRT_Speech\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\PROJECT-AV-ASR\ASRT_SpeechRecognition-master\utils\thread.py", line 47, in __next__
    return self.it.__next__()
  File "C:\PROJECT-AV-ASR\ASRT_SpeechRecognition-master\speech_model.py", line 68, in _data_generator
    wavdata, sample_rate, data_labels = data_loader.get_data(index)
  File "C:\PROJECT-AV-ASR\ASRT_SpeechRecognition-master\data_loader.py", line 88, in get_data
    wav_signal, sample_rate, _, _ = read_wav_data(self.wav_dict[mark])
  File "C:\PROJECT-AV-ASR\ASRT_SpeechRecognition-master\utils\ops.py", line 36, in read_wav_data
    wav = wave.open(filename,"rb") # 打开一个wav格式的声音文件流
  File "C:\Users\Admin\.conda\envs\ASRT_Speech\lib\wave.py", line 509, in open
    return Wave_read(f)
  File "C:\Users\Admin\.conda\envs\ASRT_Speech\lib\wave.py", line 159, in __init__
    f = builtins.open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/data/speech_data/magicdata\\train/16_3617/16_3617_20170810121301.wav'

**第二次运行：**

C:\Users\Admin\.conda\envs\ASRT_Speech\python.exe C:/PROJECT-AV-ASR/ASRT_SpeechRecognition-master/train_speech_model.py
2023-05-01 13:44:30.980721: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-01 13:44:31.250720: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21350 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4090, pci bus id: 0000:01:00.0, compute capability: 8.9
[ASRT] Compiles Model Successfully.
[ASRT Training] train epoch 1/50 .
C:\PROJECT-AV-ASR\ASRT_SpeechRecognition-master\speech_model.py:120: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  self.trained_model.fit_generator(yielddatas, num_iterate, callbacks=call_back)
Traceback (most recent call last):
  File "C:\PROJECT-AV-ASR\ASRT_SpeechRecognition-master\train_speech_model.py", line 50, in <module>
    ms.train_model(optimizer=opt, data_loader=train_data,
  File "C:\PROJECT-AV-ASR\ASRT_SpeechRecognition-master\speech_model.py", line 120, in train_model
    self.trained_model.fit_generator(yielddatas, num_iterate, callbacks=call_back)
  File "C:\Users\Admin\.conda\envs\ASRT_Speech\lib\site-packages\keras\engine\training.py", line 2209, in fit_generator
    return self.fit(
  File "C:\Users\Admin\.conda\envs\ASRT_Speech\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\PROJECT-AV-ASR\ASRT_SpeechRecognition-master\utils\thread.py", line 47, in __next__
    return self.it.__next__()
  File "C:\PROJECT-AV-ASR\ASRT_SpeechRecognition-master\speech_model.py", line 68, in _data_generator
    wavdata, sample_rate, data_labels = data_loader.get_data(index)
  File "C:\PROJECT-AV-ASR\ASRT_SpeechRecognition-master\data_loader.py", line 88, in get_data
    wav_signal, sample_rate, _, _ = read_wav_data(self.wav_dict[mark])
  File "C:\PROJECT-AV-ASR\ASRT_SpeechRecognition-master\utils\ops.py", line 36, in read_wav_data
    wav = wave.open(filename,"rb") # 打开一个wav格式的声音文件流
  File "C:\Users\Admin\.conda\envs\ASRT_Speech\lib\wave.py", line 509, in open
    return Wave_read(f)
  File "C:\Users\Admin\.conda\envs\ASRT_Speech\lib\wave.py", line 159, in __init__
    f = builtins.open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/data/speech_data/magicdata\\train/16_3684/16_3684_20170820174157.wav'

经过实际目录查看两个wav文件都是存在的。我试了只保留一个数据集，也会出现某个wav不存在的情况。

**Comment by nl8590687** [comment]
Windows系统下运行需要改配置文件里面的数据集存放路径，详情可看ASRT项目文档

**Comment by xuanxuanzl** [comment]
> Windows系统下运行需要改配置文件里面的数据集存放路径，详情可看ASRT项目文档

解决了：
asrt_config.json 里面地址全部改为绝对地址，仅仅windows下这么改。
       "train":[
            {
                "name": "thchs30_train",
                "data_list": "C:\\PROJECT-AV-ASR\\ASRT_SpeechRecognition-master\\datalist\\thchs30\\train.wav.lst",
                "data_path": "C:\\PROJECT-AV-ASR\\ASRT_SpeechRecognition-master\\data\\speech_data\\data_thchs30",
                "label_list": "C:\\PROJECT-AV-ASR\\ASRT_SpeechRecognition-master\\datalist\\thchs30\\train.syllable.txt"
            },
            {
                "name": "stcmds_train",
                "data_list": "C:\\PROJECT-AV-ASR\\ASRT_SpeechRecognition-master\\datalist\\st-cmds\\train.wav.txt",
                "data_path": "C:\\PROJECT-AV-ASR\\ASRT_SpeechRecognition-master\\data\\speech_data",
                "label_list": "C:\\PROJECT-AV-ASR\\ASRT_SpeechRecognition-master\\datalist\\st-cmds\\train.syllable.txt"
            },
            {
                "name": "primewords_train",
                "data_list": "C:\\PROJECT-AV-ASR\\ASRT_SpeechRecognition-master\\datalist\\primewords\\train.wav.lst",
                "data_path": "C:\\PROJECT-AV-ASR\\ASRT_SpeechRecognition-master\\data\\speech_data",
                "label_list": "C:\\PROJECT-AV-ASR\\ASRT_SpeechRecognition-master\\datalist\\primewords\\train.syllable.txt"
            },
            {
                "name": "aishell_train",
                "data_list": "C:\\PROJECT-AV-ASR\\ASRT_SpeechRecognition-master\\datalist\\aishell\\train.wav.lst",
                "data_path": "C:\\PROJECT-AV-ASR\\ASRT_SpeechRecognition-master\\data\\speech_data",
                "label_list": "C:\\PROJECT-AV-ASR\\ASRT_SpeechRecognition-master\\datalist\\aishell\\train.syllable.txt"
            },
            {
                "name": "aidatatang_train",
                "data_list": "C:\\PROJECT-AV-ASR\\ASRT_SpeechRecognition-master\\datalist\\aidatatang_lst\\train.wav.lst",
                "data_path": "C:\\PROJECT-AV-ASR\\ASRT_SpeechRecognition-master\\data\\speech_data",
                "label_list": "C:\\PROJECT-AV-ASR\\ASRT_SpeechRecognition-master\\datalist\\aidatatang_lst\\train.syllable.txt"
            },
            {
                "name": "magicdata_train",
                "data_list": "C:\\PROJECT-AV-ASR\\ASRT_SpeechRecognition-master\\datalist\\magicdata_lst\\train.wav.lst",
                "data_path": "C:\\PROJECT-AV-ASR\\ASRT_SpeechRecognition-master\\data\\speech_data\\magicdata",
                "label_list": "C:\\PROJECT-AV-ASR\\ASRT_SpeechRecognition-master\\datalist\\magicdata_lst\\train.syllable.txt"
            }
        ],
