### ISSUE TITLE
ValueError: Expect x to be a non-empty array or dataset.

### ISSUE THREAD

**Issue by aresword** [nl8590687/ASRT_SpeechRecognition#319]
错误信息如下

```
Traceback (most recent call last):
  File "train_speech_model.py", line 51, in <module>
    ms.train_model(optimizer=opt, data_loader=train_data,
  File "/hy-tmp/语音识别/ASRT_SpeechRecognition/speech_model.py", line 120, in train_model
    self.trained_model.fit_generator(yielddatas, num_iterate, callbacks=call_back)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1938, in fit_generator
    return self.fit(
  File "/usr/local/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1189, in fit
    raise ValueError('Expect x to be a non-empty array or dataset.')
ValueError: Expect x to be a non-empty array or dataset.
```

使用自制数据集
以下是 `train.wav.txt`，`dev.wav.txt`，`test.wav.txt`（均是相同的）
```
V1a data_aresword/train/字典树_a.wav
V1b data_aresword/train/字典树_b.wav
V1c data_aresword/train/字典树_c.wav
```
以下是 `train.syllable.txt`，`dev.syllable.txt`，`tset.syllable.txt`（均是相同的）
```
V1a zi4 dian3 shu4 shi2 xian4 xi4 jie2 ying4 she4 zi4 fu2 dao4 bian1 hao4 mei3 ge4 jie2 dian3 you3 shen1 fen4 hao4
V1b cha1 ru4 zi4 fu2 chuan4 yi1 lu4 gen1 jin4 zi3 jie2 dian3 mei2 you3 shen1 fen4 hao4 jiu4 chuang4 jian4 yi1 ge4 tong2 shi2 tong3 ji4 shu4 liang4
V1c cha2 xun2 zi4 fu2 chuan4 yi1 lu4 gen1 jin4 zi3 jie2 dian3 mei2 you3 jiu4 fan3 hui2 ling2 fou3 ze2 dao4 tou2 le5 jiu4 fan3 hui2 da2 an4
```
以下是原文：
```
V1a
字典树实现细节，映射字符到编号，每个节点有身份号

V1b
插入字符串 一路跟进，子节点没有身份号就创建一个，同时统计数量

V1c
查询字符串 一路跟进，子节点没有就返回零，否则到头了就返回答案
```

**Comment by aresword** [comment]
真相了，样本太少，batch size 太大，调为 `batch=1` 就行了

**Comment by aresword** [comment]
closed #319
