### ISSUE TITLE
运行test_mspeech.py报错

### ISSUE THREAD

**Issue by feifaxiaoming** [nl8590687/ASRT_SpeechRecognition#72]
我用了一个采样率是8000的音频文件测试报了这个错误：
Traceback (most recent call last):
  File "D:/Python/PythonHome/ASRT_v0.4.2/test_mspeech.py", line 55, in <module>
    r = ms.RecognizeSpeech_FromFile('D:\\TVSplitVideo\\Sample\\20190114\\11\\23\\gangrong.wav')
  File "D:\Python\PythonHome\ASRT_v0.4.2\SpeechModel251.py", line 379, in RecognizeSpeech_FromFile
    r = self.RecognizeSpeech(wavsignal, fs)
  File "D:\Python\PythonHome\ASRT_v0.4.2\SpeechModel251.py", line 348, in RecognizeSpeech
    data_input = GetFrequencyFeature3(wavsignal, fs)
  File "D:\Python\PythonHome\ASRT_v0.4.2\general_function\file_wav.py", line 128, in GetFrequencyFeature3
    data_line = data_line * w # 加窗
ValueError: operands could not be broadcast together with shapes (256,) (400,) 

这个用于测试用的音频文件采样率的文件必须是16000的吗？

**Comment by nl8590687** [comment]
是的，必须是16kHz的
