### ISSUE TITLE
训练好模型后，测试单个语音文件出现错误

### ISSUE THREAD

**Issue by cjjjy** [nl8590687/ASRT_SpeechRecognition#8]
Traceback (most recent call last):
  File "/home/pycharm-2017.3.3/helpers/pydev/pydevd.py", line 1668, in <module>
    main()
  File "/home/pycharm-2017.3.3/helpers/pydev/pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/pycharm-2017.3.3/helpers/pydev/pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/pycharm-2017.3.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/ASRT_SpeechRecognition-master/SpeechModel23.py", line 371, in <module>
    r = ms.RecognizeSpeech_FromFile('/home/kaldi-master/egs/thchs30/thchs30-openslr/data_thchs30/train/C4_568.wav')
  File "/home/ASRT_SpeechRecognition-master/SpeechModel23.py", line 322, in RecognizeSpeech_FromFile
    r = self.RecognizeSpeech(wavsignal, fs)
  File "/home/ASRT_SpeechRecognition-master/SpeechModel23.py", line 303, in RecognizeSpeech
    r1 = self.Predict(data_input, input_length)
  File "/home/ASRT_SpeechRecognition-master/SpeechModel23.py", line 245, in Predict
    x_in[i,0:len(data_input)] = data_input
ValueError: could not broadcast input array from shape (785,400,1) into shape (785,39,1)

**Comment by nl8590687** [comment]
你好，我刚才检查了一下，这个是个bug
在SpeechModel23.py文件里面的
```
def RecognizeSpeech(self, wavsignal, fs):
```
函数里，将
```
data_input = GetFrequencyFeature(wavsignal, fs)
```
替换为
```
data_input = GetMfccFeature(wavsignal, fs)
```
然后试一下
这个bug将很快修复，希望能帮到你。

**Comment by cjjjy** [comment]
ok,不过识别结果如果是文字就更好了
 ['you3', 'zha1', 'wen2', 'xian4', 'wen2', 'meng2', 'wan2', 'wei2', 'wai4', 'wen2', 'mang2', 'wen2', 'wei4', 'wai4', 'er4', 'lao3', 'wen2', 'ha1', 'wen2']
