### ISSUE TITLE
训练的时候，训练中会报错 Saw a non-null label (index >= num_classes - 1) following a null label, batch: 0 num_classes: 1422 labels: 671,910,489,228

### ISSUE THREAD

**Issue by feifaxiaoming** [nl8590687/ASRT_SpeechRecognition#83]
Traceback (most recent call last):
  File "D:/pythonWorkSpace/Project/speechReognized/train_mspeech.py", line 55, in <module>
    ms.TrainModel(datapath, epoch = 50, batch_size = 8, save_step = 500)
  File "D:\pythonWorkSpace\Project\speechReognized\SpeechModel261.py", line 196, in TrainModel
    self._model.fit_generator(yielddatas, save_step)
  File "D:\soft\python3\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "D:\soft\python3\lib\site-packages\keras\engine\training.py", line 2096, in fit_generator
    class_weight=class_weight)
  File "D:\soft\python3\lib\site-packages\keras\engine\training.py", line 1814, in train_on_batch
    outputs = self.train_function(ins)
  File "D:\soft\python3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2352, in __call__
    **self.session_kwargs)
  File "D:\soft\python3\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "D:\soft\python3\lib\site-packages\tensorflow\python\client\session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\soft\python3\lib\site-packages\tensorflow\python\client\session.py", line 1355, in _do_run
    options, run_metadata)
  File "D:\soft\python3\lib\site-packages\tensorflow\python\client\session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Saw a non-null label (index >= num_classes - 1) following a null label, batch: 0 num_classes: 1422 labels: 671,910,489,228
	 [[Node: ctc/CTCLoss = CTCLoss[ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ctc/Log/_305, ctc/ToInt64/_307, ctc/ToInt32_2/_309, ctc/ToInt32_1/_311)]]

**Comment by nl8590687** [comment]
您好，请问您是通过git clone下载的代码吗？由于词典dict.txt的扩充，需要将1422改到1424，然后就可以训练了

**Comment by feifaxiaoming** [comment]
ok ，谢谢了，可以训练了，但是训练到33左右，就收敛不下去了，要怎么改动，才能收敛下去呢？

**Comment by nl8590687** [comment]
需要调整学习率参数，再寻找一个比较合适的值
