### ISSUE TITLE
question two

### ISSUE THREAD

**Issue by zhaojc001** [nl8590687/ASRT_SpeechRecognition#91]
when I am training，it appears the following problem，please help me,tell me how to solve it：

[*Info] Create Model Successful, Compiles Model Successful. 
[running] train epoch 0 .
[message] epoch 0 . Have train datas 0+
Epoch 1/1
2019-03-25 08:34:25.289481: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.75GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-03-25 08:34:25.466127: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.37GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
500/500 [==============================] - 320s 641ms/step - loss: 87.5183
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition train set word error ratio:  100.0 %
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition dev set word error ratio:  100.0 %
[message] epoch 0 . Have train datas 500+
Epoch 1/1
500/500 [==============================] - 373s 746ms/step - loss: 81.0528
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition train set word error ratio:  100.0 %
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition dev set word error ratio:  100.0 %
[message] epoch 0 . Have train datas 1000+
Epoch 1/1
500/500 [==============================] - 415s 830ms/step - loss: 80.2692
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition train set word error ratio:  100.0 %
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition dev set word error ratio:  100.0 %
[message] epoch 0 . Have train datas 1500+
Epoch 1/1
500/500 [==============================] - 418s 836ms/step - loss: 78.5302
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition train set word error ratio:  100.0 %
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition dev set word error ratio:  100.0 %
[message] epoch 0 . Have train datas 2000+
Epoch 1/1
500/500 [==============================] - 419s 839ms/step - loss: 77.1008
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition train set word error ratio:  90.47619047619048 %
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition dev set word error ratio:  97.75280898876404 %
[message] epoch 0 . Have train datas 2500+
Epoch 1/1
 93/500 [====>.........................] - ETA: 5:42 - loss: 69.92382019-03-25 09:08:19.493023: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at ctc_loss_op.cc:166 : Invalid argument: Saw a non-null label (index >= num_classes - 1) following a null label, batch: 0 num_classes: 1422 labels: 671,930,31,691,130,223,691,1135,1078,427
Traceback (most recent call last):
  File "train_mspeech.py", line 47, in <module>
    ms.TrainModel(datapath, epoch = 50, batch_size = 16, save_step = 500)
  File "/usr/local/zjc/SpeechRecognition/ASRT_SpeechRecognition-master/SpeechModel251.py", line 179, in TrainModel
    self._model.fit_generator(yielddatas, save_step)
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1382, in __call__
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Saw a non-null label (index >= num_classes - 1) following a null label, batch: 0 num_classes: 1422 labels: 671,930,31,691,130,223,691,1135,1078,427
	 [[Node: ctc/CTCLoss = CTCLoss[_class=["loc:@training/Adam/gradients/ctc/CTCLoss_grad/mul"], ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ctc/Log/_297, ctc/ToInt64/_299, ctc/ToInt32_2/_301, ctc/ToInt32_1/_303)]]
	 [[Node: training/Adam/gradients/ctc/ExpandDims_grad/Shape/_317 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1052_training/Adam/gradients/ctc/ExpandDims_grad/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by nl8590687** [comment]
This may be because the number of pinyin has changed. Please try 1424 instead of 1422.

**Comment by zhaojc001** [comment]
thank you very much,the problem is solved.

**Comment by zhaojc001** [comment]
when I am training for a long time，it appears  the following problem，please once help me ：
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition dev set word error ratio:  67.07317073170732 %
[message] epoch 0 . Have train datas 14500+
Epoch 1/1
500/500 [==============================] - 407s 814ms/step - loss: 34.0991
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition train set word error ratio:  46.51162790697674 %
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition dev set word error ratio:  62.19512195121951 %
[message] epoch 0 . Have train datas 15000+
Epoch 1/1
500/500 [==============================] - 404s 808ms/step - loss: 33.4011
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition train set word error ratio:  47.368421052631575 %
Test Count:  0 / 4
Test Count:  3 / 4
*[Test Result] Speech Recognition dev set word error ratio:  77.41935483870968 %
[message] epoch 0 . Have train datas 15500+
Epoch 1/1
  9/500 [..............................] - ETA: 6:37 - loss: 32.86372019-03-26 18:34:56.530401: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 733.50MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-03-26 18:34:56.530490: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 733.50MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-03-26 18:34:56.530506: E tensorflow/stream_executor/cuda/cuda_dnn.cc:81] 
2019-03-26 18:34:56.530682: I tensorflow/stream_executor/stream.cc:4818] stream 0x7fe13ade5090 did not memzero GPU location; source: 0x7fe08d7f8ec0
Traceback (most recent call last):
  File "train_mspeech.py", line 47, in <module>
    ms.TrainModel(datapath, epoch = 50, batch_size = 16, save_step = 500)
  File "/usr/local/zjc/SpeechRecognition/ASRT_SpeechRecognition-master/SpeechModel251.py", line 180, in TrainModel
    self._model.fit_generator(yielddatas, save_step)
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1382, in __call__
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: cuDNN Backward Filter function launch failure : input shape([16,128,400,50]) filter shape([3,3,128,128])
	 [[Node: training/Adam/gradients/conv2d_6/convolution_grad/Conv2DBackpropFilter = Conv2DBackpropFilter[T=DT_FLOAT, _class=["loc:@training/Adam/gradients/dropout_5/cond/Merge_grad/cond_grad"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](dropout_5/cond/Merge, ConstantFolding/training/Adam/gradients/conv2d_6/convolution_grad/ShapeN-matshapes-1, training/Adam/gradients/conv2d_6/Relu_grad/ReluGrad)]]

**Comment by nl8590687** [comment]
It looks like hardware and cudnn computing framework and driver issues, so please explain your computer configuration to troubleshoot this issue.

**Comment by zhaojc001** [comment]
Yestorday I use the number of gpu is 3,I think the problem may be  out of memory,so I use 4 gpu once,it appears the same problem,the version of GPU that is gtx1080 8G,CUDA Version 9.0.176,CUDNN Version 7,please help me  to solve it.

**Comment by nl8590687** [comment]
What is the memory(not video memory) of your computer? This problem can occur if the memory is too small.

**Comment by ForeverRoad** [comment]
> thank you very much,the problem is solved.

How do you solve it? 1421，1422，I can't understand。I hope you can answer it.

**Comment by zhaojc001** [comment]
the memory of my computer is 64G,the GPU version is GTX1080 8G,but when i train a long time .it will appears the above error,please help me once.

**Comment by HelloNel** [comment]
maybe you can try config the GPU option in  your code, you can try:
#进行配置，使用70%的GPU
config = tf.ConfigProto()
#config.gpu_options.per_process_gpu_memory_fraction = 0.93
config.gpu_options.allow_growth=True   #不全部占满显存, 按需分配
set_session(tf.Session(config=config))
####you can try to do this config above this note

.....
####################next step####################
#start training
ms = ModelSpeech(datapath)
ms.TrainModel(datapath, epoch = xxx, batch_size = xxx, save_step = xxx)

**Comment by HelloNel** [comment]
maybe you can try config the GPU option in your code, you can try:
#进行配置，使用70%的GPU
config = tf.ConfigProto()
#config.gpu_options.per_process_gpu_memory_fraction = 0.93
config.gpu_options.allow_growth=True #不全部占满显存, 按需分配
set_session(tf.Session(config=config))
####you can try to do the config above this note

.....
####################next step####################
#start training
ms = ModelSpeech(datapath)
ms.TrainModel(datapath, epoch = xxx, batch_size = xxx, save_step = xxx)

**Comment by HelloNel** [comment]
maybe you can try config the GPU option in your code, you can try:
#进行配置，使用70%的GPU
config = tf.ConfigProto()
#config.gpu_options.per_process_gpu_memory_fraction = 0.93
config.gpu_options.allow_growth=True #不全部占满显存, 按需分配
set_session(tf.Session(config=config))
####you can try to do the config above this note

.....
####################next step####################
#start training
ms = ModelSpeech(datapath)
ms.TrainModel(datapath, epoch = xxx, batch_size = xxx, save_step = xxx)
